# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_auto_20180525_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hood_area', to='hood.Neighborhood'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hood_owner', to='hood.Profile'),
        ),
    ]
