# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0009_auto_20180528_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='user_profile',
            field=models.ForeignKey(default='false', on_delete=django.db.models.deletion.CASCADE, to='hood.Profile'),
            preserve_default=False,
        ),
    ]
