# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0007_auto_20180526_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_photo',
            field=models.ImageField(null=True, upload_to='pics/'),
        ),
    ]
